blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability
    url: https://shelby.xyz/security.txt
    about: Please report security issues privately via the process in SECURITY.md.
